### PR TITLE
 Added support for Intellij 2023.3

### PR DESCRIPTION
**Pull request by Areiser**

### CODE REVIEW

**Comment by bamarc** [comment]
Thanks for the reminder, i'll check the compatibility and see if it also needs a platform sdk update.

**Comment by Areiser** [comment]
From our testing it seems to work fine with the latest EAP. Some of us use a modified version of the plugin already since we hit some IntelliJ bugs that are fixed in the latest EAP.

**Comment by bamarc** [comment]
I have updated some dependencies as well as the platform version and uploaded an EAP version of the plugin (since 2023.3 is not stable yet) if you want to use that one. 

If more bugs come up i will try to fix them once the stable version is available.

**Comment by bamarc** [comment]
The new version is now merged and published to the stable channel. Sorry for the delay.

**Pull request closed without merging**
